name: grpc_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: any
  test: ^1.16.0

dependencies: 
  bloc: ^8.0.2
  grpc: ^3.0.2
  meta: ^1.7.0
  protobuf: ^3.1.0
